---
- name: Prepare
  hosts: all
  gather_facts: true
  tasks:
    - name: Gather facts
      ansible.builtin.setup:

    - name: Install sudo (Debian/Ubuntu)
      ansible.builtin.raw: apt-get update && apt-get install -y sudo
      when: ansible_os_family == "Debian"
      changed_when: false

    - name: Install sudo (Fedora)
      ansible.builtin.raw: dnf install -y sudo
      when: ansible_os_family == "RedHat"
      changed_when: false
